version: 0.1

phases:
  pre_build:
    commands:
      - echo "Login into ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query "Account" --output text).dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Build & push docker image"
      - docker-compose -f docker-compose-build.yml build
      - docker-compose -f docker-compose-build.yml push
      - echo "Pushing artifact"
      - docker-compose -f docker-compose-build.yml push
