version: 0.1

phases:
  pre_build:
    commands:
      - echo "Login into ECR"
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo "Build & push docker image"
      - docker-compose -f docker-compose-build.yml build
      - docker-compose -f docker-compose-build.yml push
      - echo "Pushing artifact"
      - docker-compose -f docker-compose-build.yml push
