version: "3"

services:
  analytics:
    build:
      context: ./analytics
    image: 077294513465.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:latest
    ports:
      - "5153:5153"
    restart: unless-stopped
