apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coworking-cluster
  region: us-east-1

managedNodeGroups:
  - name: coworking-cluster
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
