apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  POSTGRES_HOST: "a823d10293ef448eba9fa5ceb21a00df-596495898.us-east-1.elb.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "coworking"
