apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  POSTGRES_HOST: "a53905f6f517d4544aff42d70adb51ab-1411344514.us-east-1.elb.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "coworking"
#  POSTGRES_USER: "udacity"
#  POSTGRES_PASSWORD: "admin@123"
---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4xMjM=
